print("welcome to the gaming nickname generator")
nickname = input("what is your nickname?\n")
game = input("what is your favourite game?\n")
print("\nhere are 5 channel name ideas:\n")
print("1."+(nickname)+" "+(game))
print("2."+("the king of ")+(game))
print("3."+("the legend of ")+(game))
print("4."+(game)+(" master"))
print("5."+(game)+(" ")+(nickname))